### ISSUE TITLE
routines:SSL_CTX_use_certificate:ee key too small

### ISSUE THREAD

**Issue by senolatac** [mlandauer/cuttlefish#441]
Is it possible to disable TLS on development?

I try to use cuttlefish as SMTP-GATEWAY with [mail-docker](https://github.com/muety/mailwhale)

So my config.yml looks like:

```
smtp:
  host: 'cuttlefish_smtp'
  port: 2525
  username: 'acting_twins_2'
  password: '...'
  tls: false                           # Whether to connect via SSL/TLS (set 'false' for STARTTLS)
  skip_verify_tls: false              # Whether to trust self-signed certificates
```

then I try to send mail from mail-docker but cuttlefish-smtp gives error: 
```
140714303958848:error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small:../ssl/ssl_rsa.c:301:
140714303958848:error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../ssl/statem/statem_srvr.c:2283:
```

Is there any suggestion?
